### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by tasoss** [anubhavmaity/Sports-Type-Classifier#1]
Hello.
I get this message when i try to lfs fetch the models...
Any ideas?
Thanks!

**Comment by anubhavmaity** [comment]
You can access the model and data from [here](https://www.dropbox.com/h?preview=sports-type-classifier-data.7z).

**Comment by tasoss** [comment]
Thank you very much!
ps: Do you accept pull requests?(corrections and new photos?)

**Comment by anubhavmaity** [comment]
Yes, I can accept pull request in terms of data and code.
Is the dropbox link not working?

**Comment by anubhavmaity** [comment]
Opening the issue. Once you confirm, will close it.

**Comment by tasoss** [comment]
The link is fine!
Thanks!
