### ISSUE TITLE
Unable to load the dataset even after downloading the data

### ISSUE THREAD

**Issue by Nakul93** [anubhavmaity/Sports-Type-Classifier#2]
I have saved the data from dropbox on to Sports-Type-Classifier-master folder but still I get the error y has 0 samples as shown below
[INFO] loading images...
Traceback (most recent call last):
  File "train.py", line 80, in <module>
    labels = lb.fit_transform(labels)
  File "C:\Users\nn243\AppData\Local\conda\conda\envs\opencv-env\lib\site-packages\sklearn\preprocessing\label.py", line 439, in fit_transform
    return self.fit(y).transform(y)
  File "C:\Users\nn243\AppData\Local\conda\conda\envs\opencv-env\lib\site-packages\sklearn\preprocessing\label.py", line 413, in fit
    raise ValueError('y has 0 samples: %r' % y)
ValueError: y has 0 samples: array([], dtype=float64)

FYI: I am using a windows machine

**Comment by anubhavmaity** [comment]
Can you share the code snippet?

**Comment by Nakul93** [comment]
So I used the code from pyimagesearch here is the link to that
https://www.pyimagesearch.com/2019/07/15/video-classification-with-keras-and-deep-learning/

**Comment by anubhavmaity** [comment]
Have you downloaded the dataset?  The dataset is no more in the repo.

**Comment by Nakul93** [comment]
yes I have downloaded the dataset from dropbox. Can you tell me if this code is workable?

**Comment by anubhavmaity** [comment]
I don't know because I am not the author of the code in the article referenced in this issue. You have to ask the author.
