### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by m3m3-chan** [anubhavmaity/Sports-Type-Classifier#3]
Hello, 
I downloaded the file referenced in #1 but when I open the models folder inside, I find _res50_stage.pth_ files and no _activity.model_ file ?

Would you mind sharing the links for the model again please?

thanks

**Comment by anubhavmaity** [comment]
May I know why activity.model file is required?

**Comment by m3m3-chan** [comment]
Hello @anubhavmaity 
 Thanks for the prompt response!
I want to use the model your pretrained  to try to detect another type of sport.
Since I'm a newbie in all these ML stuff, I got confused to find _.pth_ files in the model folder, I assumed this is not the activity detecting model that I can use to run the code which is why I asked for the _.model_ file. 
If the model is .pth file , can you give guidance on how to run your code  using the .pth files? or is it that we have to train our own model?

Regards,

**Comment by anubhavmaity** [comment]
In PyTorch, the models are saved as .pth extension. You can read more about it [here](https://forums.fast.ai/t/which-format-is-better-for-pytorch-saved-model/5018). 
You can read the notebook to get the idea of loading and using the model. 
I have used [fastai api](https://docs.fast.ai/) to do the same.
You can also use this model to fine-tune on your dataset.
Let me know if you face any difficulties.

**Comment by m3m3-chan** [comment]
Thank you very much for the explanation!
I will try that & let you know

cheers,
