### ISSUE TITLE
Can't find the dataset

### ISSUE THREAD

**Issue by joel1895** [anubhavmaity/Sports-Type-Classifier#5]
Hi, I can't find the sports classification dataset. I read somewhere that you had moved it some other location. I tried locating it, but no luck. I read the readme.md..where i am taken to someone else's repo. So we have to make our dataset like you did?

**Comment by drhoffma** [comment]
I'll second this. Can you  please inform us where the dataset is now located?

**Comment by drhoffma** [comment]
The data is available at this commit: https://github.com/anubhavmaity/Sports-Type-Classifier/tree/44513762e9ebbabeb64b55c5da5401fe57b6d85b

**Comment by anubhavmaity** [comment]
As mentioned in the README, please download the datasets using gi2ds
